development:
  adapter: postgresql
  host: localhost
  username: rails_user
  database: cashflowprojector_dev

test:
  adapter: postgresql
  host: localhost
  username: rails_user
  database: cashflowprojector_test
