development:
  adapter: postgresql
  host: postgresql
  username: rails_user
  database: cashflowprojector_dev

test:
  adapter: postgresql
  host:  postgresql
  username: rails_user
  database: cashflowprojector_test
